"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.css";
import { configureChains, sepolia, WagmiConfig, createClient } from "wagmi";
import { publicProvider } from "wagmi/providers/public";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const { provider, webSocketProvider } = configureChains(
    [sepolia],
    [publicProvider()]
  );

  const client = createClient({
    autoConnect: true,
    provider,
    webSocketProvider,
  });
  return (
    <html lang="en">
      <WagmiConfig client={client}>
        <body className={inter.className}>{children}</body>
      </WagmiConfig>
    </html>
  );
}
